### ISSUE TITLE
benefits over nsbundle?

### ISSUE THREAD

**Issue by EXC-BAD-ACCESS** [nicklockwood/StandardPaths#18]
i was thinking about using this library but it sort of appears that it is no longer being maintained, so when i went to roll my own solution i found myself wondering why you can't just do something like this and let NSBundle's internals take care of it (swift 3):

```
func normalizedPathForFile(_ path:String) -> String {
    let base = path.stringByDeletingLastPathComponent()
    let file = path.lastPathComponent().stringByDeletingPathExtension()
    let ext = path.pathExtension()
    return Bundle(path: base)?.path(forResource:file, ofType:ext) ?? path
}
```

in my testing i put files named "plugin\~iphone.xml" and "plugin\~ipad.xml" in the documents directory and called it like: 
`normalizedPathForFile("/full/path/to/documents/dir/plugin.xml")`

and it found the correct files on both iphone and ipad

**Comment by nicklockwood** [comment]
@EXC-BAD-ACCESS it's not unmaintained, but yes, the reason it's updated infrequently is because it's not as useful as it used to be.

StandardPaths uses NSBundle internally, so it's not really a case of either/or. StandardPaths basically extends the functionality of NSBundle to include additional features such as:

* Loading images outside of the bundle (e.g. ~/Documents) based on the device type, resolution, etc
* Loading different nibs and storyboards automatically based on the device type, resolution, etc

NSBundle only lets you do this for certain file/suffix combinations, whereas StandardPaths supports all suffixes for all files, wherever they are located.
